- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts
  shell: "grep -qxF \"{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ inventory_hostname }}\" /etc/hosts | echo \"{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ inventory_hostname }}\" >> /etc/hosts "
  with_items: "{{ cluster_hostnames }}"
  register: cmdln
  check_mode: no

- name: Update ubuntu
  apt: update_cache=yes
  tags: slave_only

- name: Install NFS packages
  apt:
    pkg:
      - build-essential
      - nfs-common
      - nfs-kernel-server 
    state: present
  tags: slave_only
