- name: Create munge group
  group:
    name: munge
    state: present
    gid: 3456

- name: Create munge user
  user:
    name: "munge"
    uid: 3456
    group: munge
    password: "{{ munge_user_passwd | password_hash('sha512') }}"
    state: present
    shell: /sbin/nologin       
    system: no             
    createhome: yes        
    home: /var/lib/munge

- name: Create slurm group
  group:
    name: slurm
    state: present
    gid: 3457

- name: Create slurm user
  user:
    name: "slurm"
    uid: 3457
    group: slurm
    password: "{{ slurm_user_passwd | password_hash('sha512') }}"
    state: present
    shell: /bin/bash       
    system: no             
    createhome: yes        
    home: /var/lib/slurm

- name: Update ubuntu
  apt: update_cache=yes

- name: Install nfs and munge packages
  apt:
    pkg:
      - build-essential
      - nfs-common
      - nfs-kernel-server 
      - munge 
      - libmunge2 
      - libmunge-dev
    state: present

- name: Create munge key for authentication ...
  command: /usr/sbin/create-munge-key -f

- name: Grant the proper permissions to the munge folders
  file: 
    path: '{{ item }}'
    owner: munge
    group: munge
    mode: '0700'
    loop:
      - /etc/munge/ 
      - /var/log/munge/ 
      - /var/lib/munge/ 

- name: Grant the proper permissions to the munge /run/munge folder
  file:
    path: '{{ item }}'
    owner: munge
    group: munge
    mode: '0755'
    loop:
      - /run/munge

- name: Make sure munge service unit is running
  service:
    state: started
    name: munge

- name: Install slurmctld and slurmd packages
  apt:
    pkg:
      - slurm-wlm
    state: present

- name: Create /etc/slurm-llnl/slurm.conf
  template:
    src: slurm.conf.j2
    dest: /etc/slurm-llnl/slurm.conf
    owner: slurm
    group: slurm
    mode: 755

# - name: Make sure slurmctld service unit is running
#   service:
#     state: started
#     name: slurmctld

- name: Make sure slurmd service unit is running
  service:
    state: started
    name: slurmd