- name: Create/delete users
  user:
    name: "{{ item }}"
    password: "{{ users_passwd | password_hash('sha512') }}"
    shell: /bin/bash 
    system: no             
    createhome: yes        
    home: /home/{{ item }}
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
    state: "{{ users_state }}"
  with_sequence: start={{ users_seq_start }} end={{ users_seq_end }} format={{ users_seq_format }}

- name: Create authorized_keys file
  file:
    path: /home/{{ item }}/.ssh/authorized_keys
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0600
    state: touch
  with_sequence: start={{ users_seq_start }} end={{ users_seq_end }} format={{ users_seq_format }}

- name: Place public key into authorized_keys
  become_user: "{{ item }}"
  shell: cat /home/{{ item }}/.ssh/id_rsa.pub >> /home/{{ item }}/.ssh/authorized_keys
  with_sequence: start={{ users_seq_start }} end={{ users_seq_end }} format={{ users_seq_format }}
