---
- name: Setting up master node
  hosts:
    - galaxy-2
  user: vagrant
  become: true
  roles: 
    - basic
    - master
  vars:
    cluster_name: galaxy.cluster
    master_node_hostname: galaxy-1
    munge_user_passwd: jlDmPv
    slurm_user_passwd: jlDmPv
    # Hosts for slurm.conf file
    hosts:
      - { name: "galaxy-1", ip: 10.0.0.2, cpus: 1, mem: 500 }
      - { name: "galaxy-2", ip: 10.0.0.3, cpus: 1, mem: 500 }
      - { name: "galaxy-3", ip: 10.0.0.4, cpus: 1, mem: 500 }

    nfs_exports:
      # users accounts
      - /home *(rw,sync,no_root_squash,no_subtree_check)
      # munge authentication keys
      - /etc/munge *(rw,sync,no_root_squash,no_subtree_check)
      # for slurm.confg and gres.conf files 
      - /etc/slurm-llnl *(rw,sync,no_root_squash,no_subtree_check)

- name: Setting up slave nodes
  hosts: 
    - galaxy-3
  user: vagrant
  become: true
  roles: 
    - role: basic
      tags: slave_only
    - slave
  vars:
    cluster_name: galaxy.cluster
    master_node_hostname: galaxy-1
    munge_user_passwd: jlDmPv
    slurm_user_passwd: jlDmPv
    # Hosts for slurm.conf file
    hosts:
      - { name: "galaxy-1", ip: 10.0.0.2, cpus: 1, mem: 500 }
      - { name: "galaxy-2", ip: 10.0.0.3, cpus: 1, mem: 500 }
      - { name: "galaxy-3", ip: 10.0.0.4, cpus: 1, mem: 500 }
    nfs_imports:
      - { name: /home, src: 'galaxy-2:/home', type: nfs }
      - { name: /etc/munge, src: 'galaxy-2:/etc/munge', type: nfs }
      - { name: /etc/slurm-llnl, src: 'galaxy-2:/etc/slurm-llnl', type: nfs }