- name: Setting up slave nodes
  hosts: 
    - galaxy-3
  user: vagrant
  become: true
  roles: 
    - basic
    - slave
  vars:
    cluster_name: galaxy.cluster
    master_node_hostname: openmp-tutorial-00
    munge_user_passwd: jlDmPv
    slurm_user_passwd: jlDmPv
    # Hosts for slurm.conf file
    hosts:
      - { name: "openmp-tutorial-1", men: 187000, cpus: 48, ip: 10.140.83.180 }
      - { name: "openmp-tutorial-2", men: 187000, cpus: 48, ip: 10.140.82.20 }
      - { name: "openmp-tutorial-3", men: 187000, cpus: 48, ip: 10.140.82.70 }
      - { name: "openmp-tutorial-4", men: 187000, cpus: 48, ip: 10.140.83.19 }
      - { name: "openmp-tutorial-5", men: 187000, cpus: 48, ip: 10.140.83.52 }
      - { name: "openmp-tutorial-6", men: 187000, cpus: 48, ip: 10.140.82.253 }
      - { name: "openmp-tutorial-7", men: 187000, cpus: 48, ip: 10.140.83.151 }
    nfs_imports:
      - { name: /home, src: 'openmp-tutorial-00:/home', type: nfs }
      - { name: /etc/munge, src: 'openmp-tutorial-00:/etc/munge', type: nfs }
      #- { name: /etc/slurm-llnl, src: 'galaxy-2:/etc/slurm-llnl', type: nfs }