- name: create some test users
  ansible.builtin.user:
    name: "{{ item }}"
    state: "{{ users_state }}"
  with_sequence: start={{ users_seq_start }} end={{ users_seq_end }} format={{ users_seq_format }}