- name: Install Python prerequisites
  command: | 
    python3 -m pip install \
      graphviz \
      dask[complete] \
      jupyterlab \
      dask-labextension \
      dask-jobqueue \
      memory_profiler \
      coiled
  register: cmdln
  check_mode: no