# - name: Pull vagrant box
#   become_user: "{{ user_name }}"
#   command: vagrant box add ubuntu/xenial64

- name: Remove HTCondor-Docker-OpenMP directory if present
  become_user: "{{ user_name }}"
  file:
    path: ~/HTCondor-Docker-OpenMP
    state: absent

- name: Remove HTCondor-Docker-OpenMP directory if present
  become_user: "{{ user_name }}"
  file:
    path: ~/VirtualBox VMs
    state: absent


- name: Clone HTCondor-Docker-OpenMP
  become_user: "{{ user_name }}"
  git:
    repo: https://github.com/DonAurelio/HTCondor-Docker-OpenMP.git
    dest: ~/HTCondor-Docker-OpenMP

- name: Vagrant UP
  become_user: "{{ user_name }}"
  command: vagrant up
  args:
    chdir: ~/HTCondor-Docker-OpenMP