---
- name: Setting up master node
  hosts:
    - m
  user: clouduser
  become: true
  roles: 
    - basic
#     - master

# - name: Setting up slave nodes
#   hosts: 
#     - n
#     - o
#     - p
#     - k 
#   user: clouduser
#   become: true
#   roles: 
#     - basic
#     - slave
