---
- name: Setting up master node
  hosts:
    - o
  user: clouduser
  become: true
  roles: 
    - basic
    - master
  vars:
    mpi_temp_dir: /tmp/openmpi
    mpi_inst_dir: /opt/openmpi-3.1.2
    mpi_test_dir: /tmp/openmpi-test
    mpi_user_name: mpiuser
    mpi_master_hostname: ss2023-00

